apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: defult

  source:
    repoURL: https://github.com/ToviKolitz/argodemoconfig.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.defult.svc
    namespace: myapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true